### ISSUE TITLE
Unexpected token error when minifying

### ISSUE THREAD

**Issue by mith** [Doodle3D/Doodle3D-Slicer#24]
The new progress-promise dependency causes an error when minifying with uglify:

```
remote: err  Error: SyntaxError: Unexpected token: name (ProgressPromise)
remote:     at minify (/tmp/build_70d890ca2e787282b88cd17b3d18b94a/node_modules/systemjs-builder/lib/output.js:79:11)
remote:     at exports.writeOutputs (/tmp/build_70d890ca2e787282b88cd17b3d18b94a/node_modules/systemjs-builder/lib/output.js:153:14)
remote:     at /tmp/build_70d890ca2e787282b88cd17b3d18b94a/node_modules/systemjs-builder/lib/builder.js:805:14
remote:     at tryCatcher (/tmp/build_70d890ca2e787282b88cd17b3d18b94a/node_modules/bluebird/js/release/util.js:16:23)
remote:     at Promise._settlePromiseFromHandler (/tmp/build_70d890ca2e787282b88cd17b3d18b94a/node_modules/bluebird/js/release/promise.js:512:31)
remote:     at Promise._settlePromise (/tmp/build_70d890ca2e787282b88cd17b3d18b94a/node_modules/bluebird/js/release/promise.js:569:18)
remote:     at Promise._settlePromise0 (/tmp/build_70d890ca2e787282b88cd17b3d18b94a/node_modules/bluebird/js/release/promise.js:614:10)
remote:     at Promise._settlePromises (/tmp/build_70d890ca2e787282b88cd17b3d18b94a/node_modules/bluebird/js/release/promise.js:693:18)
remote:     at Async._drainQueue (/tmp/build_70d890ca2e787282b88cd17b3d18b94a/node_modules/bluebird/js/release/async.js:133:16)
remote:     at Async._drainQueues (/tmp/build_70d890ca2e787282b88cd17b3d18b94a/node_modules/bluebird/js/release/async.js:143:10)
remote:     at Immediate.Async.drainQueues (/tmp/build_70d890ca2e787282b88cd17b3d18b94a/node_modules/bluebird/js/release/async.js:17:14)
remote:     at runCallback (timers.js:672:20)
remote:     at tryOnImmediate (timers.js:645:5)
remote:     at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by peteruithoven** [comment]
I've opened an issue at the package's repo: https://github.com/numtel/progress-promise/issues/4
